CREATE TABLE CLIENTES(
    IDCLIENTE BIGINT AUTO_INCREMENT NOT NULL,
    NOMECLIENTE VARCHAR(60) NOT NULL,
    DTANASCCLIENTE VARCHAR(15) NOT NULL,
    EMAILCLIENTE VARCHAR(60),
    CPFCLIENTE  VARCHAR(14) NOT NULL,
    CIDADECLIENTE VARCHAR(60),
    RUACLIENTE VARCHAR(60),
    BAIRROCLIENTE VARCHAR(60),
    NUMCASACLIENTE VARCHAR(10),
    CONTATOCLIENTE VARCHAR(20),
    COMPLCLIENTE VARCHAR(60),
    IDEMPRESA BIGINT,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE),
    CONSTRAINT FK_EMPRESA_CLIENTE FOREIGN KEY (IDEMPRESA) REFERENCES empresas(IDEMPRESA),
    CONSTRAINT UN_CPF UNIQUE (CPFCLIENTE)
);