CREATE TABLE PRESTACAO_SERVICOS(
    IDSERVICO BIGINT AUTO_INCREMENT NOT NULL,
    VALORSERVICO NUMERIC(11,2) NOT NULL,
    DATASERVICO VARCHAR(15) NOT NULL,
    DETALHAMENTOSERVICO VARCHAR(60) NOT NULL,
    VERIFSERVICO BOOLEAN,
    IDEMPRESA BIGINT,	
    CONSTRAINT PK_SERVICO PRIMARY KEY(IDSERVICO),
    CONSTRAINT FK_EMPRESA_PESTACAOSERVICO FOREIGN KEY(IDEMPRESA) REFERENCES empresas(IDEMPRESA)
);